name: Deploy to WordPress.org

on:
  release:
    types: [published]

jobs:
  new-release:
    name: New release
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
              php-version: '7.3'
              coverage: none
              tools: composer

      - name: Install dependencies
        run: |
          composer install --no-progress --no-dev --no-ansi --prefer-dist --no-interaction --no-scripts --optimize-autoloader

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@2.1.1
        env:
          SLUG: 'wp-widget-disable'
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
